# Generated by Django 3.2 on 2021-05-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('iva', models.DecimalField(decimal_places=5, max_digits=10)),
                ('sub_total', models.FloatField()),
                ('total', models.BigIntegerField()),
            ],
            options={
                'db_table': 'boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad_prod', models.BigIntegerField()),
                ('id_usuario', models.BigIntegerField()),
                ('id_producto', models.BigIntegerField()),
            ],
            options={
                'db_table': 'carrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.FloatField(primary_key=True, serialize=False)),
                ('rut_cli', models.CharField(max_length=40)),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('fono', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('id_detalle', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad_prod', models.BigIntegerField()),
                ('precio_uni', models.BigIntegerField()),
                ('precio_total', models.BigIntegerField()),
            ],
            options={
                'db_table': 'detalle_boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id_detalle', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad_prod', models.BigIntegerField()),
                ('precio_uni', models.BigIntegerField()),
                ('precio_total', models.BigIntegerField()),
            ],
            options={
                'db_table': 'detalle_factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id_detalle', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad_prod', models.BigIntegerField()),
                ('precio_uni', models.BigIntegerField()),
                ('precio_total', models.BigIntegerField()),
            ],
            options={
                'db_table': 'detalle_orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id_domicilio', models.BigIntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=30)),
                ('comuna', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'domicilio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.FloatField(primary_key=True, serialize=False)),
                ('rut_emp', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoCompra',
            fields=[
                ('id_estado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'estado_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoOrden',
            fields=[
                ('id_estado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado_orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('iva', models.DecimalField(decimal_places=5, max_digits=10)),
                ('sub_total', models.FloatField()),
                ('total', models.BigIntegerField()),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FamiliaProd',
            fields=[
                ('id_familia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'familia_prod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FotoProd',
            fields=[
                ('id_foto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, upload_to='Productos/')),
            ],
            options={
                'db_table': 'foto_prod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_pago', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'metodo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_orden', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('total', models.BigIntegerField()),
            ],
            options={
                'db_table': 'orden_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('vencimiento', models.DateField()),
                ('precio', models.BigIntegerField()),
                ('stock', models.BigIntegerField()),
                ('stock_critico', models.BigIntegerField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.FloatField(primary_key=True, serialize=False)),
                ('rut_provee', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=40)),
                ('celular', models.BigIntegerField()),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id_rubro', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'rubro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id_tipo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProd',
            fields=[
                ('id_tipo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_prod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
